// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	repository2 "github.com/shwatanap/workout-wizard-api/src/infra/api/repository"
	"github.com/shwatanap/workout-wizard-api/src/infra/db/repository"
	"github.com/shwatanap/workout-wizard-api/src/presen/handler"
	"github.com/shwatanap/workout-wizard-api/src/usecase"
)

// Injectors from wire.go:

func InitMenuHandler(driver *sql.DB) handler.MenuHandler {
	iWorkoutRepository := repository.NewWorkoutRepository(driver)
	iMenuRepository := repository.NewMenuRepository(driver)
	iMenuExternalRepository := repository2.NewMenuExternalRepository()
	menuUsecase := usecase.NewMenuUsecase(iWorkoutRepository, iMenuRepository, iMenuExternalRepository)
	menuHandler := handler.NewMenuHandler(menuUsecase)
	return menuHandler
}
