// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: menu.sql

package sqlc

import (
	"context"
)

const createMenu = `-- name: CreateMenu :exec
INSERT INTO menus (
	user_id,
	target,
	comment
) VALUES (
	?, ?, ?
)
`

type CreateMenuParams struct {
	UserID  int32  `json:"user_id"`
	Target  string `json:"target"`
	Comment string `json:"comment"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) error {
	_, err := q.db.ExecContext(ctx, createMenu, arg.UserID, arg.Target, arg.Comment)
	return err
}
