// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import ()

type Menu struct {
	ID      int32  `json:"id"`
	UserID  int32  `json:"user_id"`
	Target  string `json:"target"`
	Comment string `json:"comment"`
}
