// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: workout.sql

package sqlc

import (
	"context"
)

const createWorkout = `-- name: CreateWorkout :exec
INSERT INTO workouts (
	menu_id,
	name,
	detail
) VALUES (
	?, ?, ?
)
`

type CreateWorkoutParams struct {
	MenuID int32  `json:"menu_id"`
	Name   string `json:"name"`
	Detail string `json:"detail"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, createWorkout, arg.MenuID, arg.Name, arg.Detail)
	return err
}

const getCreatedWorkoutID = `-- name: GetCreatedWorkoutID :one
SELECT LAST_INSERT_ID()
`

func (q *Queries) GetCreatedWorkoutID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCreatedWorkoutID)
	var last_insert_id int64
	err := row.Scan(&last_insert_id)
	return last_insert_id, err
}
